name: macos-spm
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup GLFW
        run: |
          brew install glfw

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v

      - name: Build release
        run: swift build -c release -v
